"""In-memory session state for SalomeMCP.

Each tool call records a `GeomEntry` or `MeshEntry`, which carries the
fragment of Salome Python it should emit. `render_script()` stitches
everything together into a runnable `salome -t` script.
"""
from __future__ import annotations

import json
import re
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Iterable

_SAFE = re.compile(r"[^A-Za-z0-9_]")


def to_var(name: str) -> str:
    """Turn a user-facing name into a safe Python identifier."""
    if not name or not name.strip():
        raise ValueError("Object name must be a non-empty string.")
    var = _SAFE.sub("_", name.strip())
    if var[0].isdigit():
        var = "_" + var
    return var


@dataclass
class GeomEntry:
    name: str
    var: str
    kind: str
    params: dict[str, Any]
    code: str

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class MeshEntry:
    name: str
    var: str
    geometry: str
    params: dict[str, Any]
    code: str

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class Session:
    workdir: Path = field(default_factory=lambda: Path.cwd() / ".salome_mcp")
    objects: dict[str, GeomEntry] = field(default_factory=dict)
    meshes: dict[str, MeshEntry] = field(default_factory=dict)
    notes: list[str] = field(default_factory=list)
    exports: list[dict[str, str]] = field(default_factory=list)

    # ----- bookkeeping -----
    def reset(self) -> None:
        self.objects.clear()
        self.meshes.clear()
        self.notes.clear()
        self.exports.clear()

    def require(self, name: str) -> GeomEntry:
        if name not in self.objects:
            existing = ", ".join(sorted(self.objects)) or "(none)"
            raise KeyError(f"Object '{name}' not found. Existing: {existing}")
        return self.objects[name]

    def fresh_var(self, base: str) -> str:
        var = to_var(base)
        used = {e.var for e in self.objects.values()} | {
            m.var for m in self.meshes.values()
        }
        if var not in used:
            return var
        i = 1
        while f"{var}_{i}" in used:
            i += 1
        return f"{var}_{i}"

    # ----- mutations -----
    def add_object(
        self,
        name: str,
        kind: str,
        params: dict[str, Any],
        code_lines: Iterable[str],
    ) -> GeomEntry:
        if name in self.objects:
            raise ValueError(f"Object '{name}' already exists.")
        if name in self.meshes:
            raise ValueError(f"Name '{name}' is already used by a mesh.")
        var = self.fresh_var(name)
        rendered = [ln.replace("{var}", var) for ln in code_lines]
        rendered.append(f"geompy.addToStudy({var}, {name!r})")
        entry = GeomEntry(
            name=name, var=var, kind=kind,
            params=params, code="\n".join(rendered),
        )
        self.objects[name] = entry
        return entry

    def add_mesh(
        self,
        name: str,
        geometry: str,
        params: dict[str, Any],
        code_lines: Iterable[str],
    ) -> MeshEntry:
        if name in self.meshes:
            raise ValueError(f"Mesh '{name}' already exists.")
        if name in self.objects:
            raise ValueError(f"Name '{name}' is already used by a geometry.")
        if geometry not in self.objects:
            raise KeyError(f"Geometry '{geometry}' does not exist.")
        var = self.fresh_var(f"mesh_{name}")
        geom_var = self.objects[geometry].var
        rendered = []
        for ln in code_lines:
            rendered.append(ln.replace("{var}", var).replace("{geom_var}", geom_var))
        rendered.append(f"smesh.SetName({var}.GetMesh(), {name!r})")
        entry = MeshEntry(
            name=name, var=var, geometry=geometry,
            params=params, code="\n".join(rendered),
        )
        self.meshes[name] = entry
        return entry

    def add_note(self, text: str) -> None:
        self.notes.append(text.replace("\n", " ").strip())

    def add_export(self, kind: str, source: str, path: str) -> None:
        self.exports.append({"kind": kind, "source": source, "path": path})

    # ----- rendering -----
    def render_script(self) -> str:
        L: list[str] = []
        L.append("# Generated by SalomeMCP")
        L.append("# Run with:  salome -t this_script.py")
        L.append("import math, os, sys")
        L.append("import salome")
        L.append("salome.salome_init()")
        L.append("import GEOM")
        L.append("from salome.geom import geomBuilder")
        L.append("geompy = geomBuilder.New()")
        L.append("import SMESH")
        L.append("from salome.smesh import smeshBuilder")
        L.append("smesh = smeshBuilder.New()")
        L.append("")
        L.append("# Reference geometry")
        L.append("O  = geompy.MakeVertex(0, 0, 0)")
        L.append("OX = geompy.MakeVectorDXDYDZ(1, 0, 0)")
        L.append("OY = geompy.MakeVectorDXDYDZ(0, 1, 0)")
        L.append("OZ = geompy.MakeVectorDXDYDZ(0, 0, 1)")
        L.append("")

        if self.notes:
            L.append("# --- Design intent ---")
            for n in self.notes:
                L.append(f"# {n}")
            L.append("")

        if self.objects:
            L.append("# --- Geometry ---")
            for entry in self.objects.values():
                L.append(f"# {entry.kind}: {entry.name}")
                L.append(entry.code)
                L.append("")

        if self.meshes:
            L.append("# --- Meshes ---")
            for entry in self.meshes.values():
                L.append(f"# mesh on {entry.geometry}")
                L.append(entry.code)
                L.append("")

        if self.exports:
            L.append("# --- Exports ---")
            for exp in self.exports:
                kind, src, path = exp["kind"], exp["source"], exp["path"]
                if kind == "step":
                    var = self.objects[src].var
                    L.append(f"geompy.ExportSTEP({var}, {path!r}, GEOM.LU_METER)")
                elif kind == "brep":
                    var = self.objects[src].var
                    L.append(f"geompy.ExportBREP({var}, {path!r})")
                elif kind == "stl":
                    var = self.objects[src].var
                    L.append(f"geompy.ExportSTL({var}, {path!r}, True)")
                elif kind == "med":
                    var = self.meshes[src].var
                    L.append(f"{var}.ExportMED({path!r})")
                elif kind == "unv":
                    var = self.meshes[src].var
                    L.append(f"{var}.ExportUNV({path!r})")
                elif kind == "stl_mesh":
                    var = self.meshes[src].var
                    L.append(f"{var}.ExportSTL({path!r}, True)")
            L.append("")

        L.append("if salome.sg.hasDesktop():")
        L.append("    salome.sg.updateObjBrowser()")
        L.append("")
        return "\n".join(L)

    # ----- persistence -----
    def to_dict(self) -> dict[str, Any]:
        return {
            "workdir": str(self.workdir),
            "objects": {n: e.to_dict() for n, e in self.objects.items()},
            "meshes": {n: e.to_dict() for n, e in self.meshes.items()},
            "notes": list(self.notes),
            "exports": list(self.exports),
        }

    def save(self, path: Path) -> None:
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(self.to_dict(), indent=2))

    @classmethod
    def load(cls, path: Path) -> "Session":
        data = json.loads(Path(path).read_text())
        s = cls(workdir=Path(data.get("workdir", ".")))
        for n, d in data.get("objects", {}).items():
            s.objects[n] = GeomEntry(**d)
        for n, d in data.get("meshes", {}).items():
            s.meshes[n] = MeshEntry(**d)
        s.notes = list(data.get("notes", []))
        s.exports = list(data.get("exports", []))
        return s
